### ISSUE TITLE
for some reason the tools for drawing on the bottom not showing 

### ISSUE THREAD

**Issue by dani2906** [poluektov/pdfkit-ink-annotations#1]

**Comment by usman-pucit** [comment]
The same issue can't see drawing tools.

**Comment by chawatvish** [comment]
Seem like he didn't provide on storyboard. He created PDFDrawer.

**Comment by poluektov** [comment]
Yes, the drawing tools were not included in the example app. Please, check the latest commit, I'd added the example!
